openapi: 3.0.0
info:
  title: Lesson Materials API
  description: API contracts for managing lesson materials (attachments)
  version: 1.0.0

paths:
  /api/v1/system/upload-attachment-url/:
    post:
      summary: Get presigned URL for lesson material upload
      description: Returns a presigned URL for uploading a file to S3, specifically for lesson materials
      tags:
        - Upload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - file_name
                - content_type
              properties:
                file_name:
                  type: string
                  description: Original filename with extension
                  example: lesson-notes.pdf
                content_type:
                  type: string
                  description: MIME type of the file
                  example: application/pdf
                folder:
                  type: string
                  description: Folder for organizing files
                  default: lesson-materials
                  example: lesson-materials
      responses:
        '200':
          description: Presigned URL generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  upload_url:
                    type: string
                    format: uri
                    description: Presigned URL for uploading file (PUT request)
                  key:
                    type: string
                    description: S3 object key
                  public_url:
                    type: string
                    format: uri
                    description: Public URL to access file after upload
                  expires_in:
                    type: integer
                    description: Expiration time in seconds
                  file_name:
                    type: string
                    description: Generated unique filename
        '400':
          description: Invalid request (invalid content type, file name, etc.)
        '401':
          description: Unauthorized

  /api/v1/courses/{courseId}/chapters/{chapterId}/lessons/{lessonId}/:
    patch:
      summary: Update lesson (including materials)
      description: Updates a lesson, including its materials array. Materials array is sent in full (not incremental).
      tags:
        - Lessons
      parameters:
        - name: courseId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: chapterId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: lessonId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                video_url:
                  type: string
                # ... other lesson fields
                materials:
                  type: array
                  description: Array of lesson materials. Send full array on update.
                  items:
                    $ref: '#/components/schemas/LessonMaterial'
      responses:
        '200':
          description: Lesson updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'
        '400':
          description: Invalid request data
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (not lesson owner or admin)
        '404':
          description: Lesson not found

    get:
      summary: Get lesson details (including materials)
      description: Retrieves lesson details with associated materials. Materials include access control gating.
      tags:
        - Lessons
      parameters:
        - name: courseId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: chapterId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: lessonId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Lesson retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'
        '401':
          description: Unauthorized
        '404':
          description: Lesson not found

components:
  schemas:
    LessonMaterial:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Material ID (omit for new materials, include for updates)
        title:
          type: string
          description: Display name for the material
          maxLength: 255
        description:
          type: string
          description: Additional description
          nullable: true
        file_url:
          type: string
          format: uri
          description: Public URL of the uploaded file (null if no access)
          nullable: true
        file_type:
          type: string
          description: MIME type of the file
          example: application/pdf
        file_size:
          type: integer
          description: File size in bytes
          minimum: 0
        uploaded_at:
          type: string
          format: date-time
          description: Upload timestamp (read-only)
        uploaded_by:
          type: integer
          description: User ID of uploader (read-only)
        has_access:
          type: boolean
          description: Whether current user has access to this material (read-only)
      required:
        - title
        - file_url
        - file_type
        - file_size

    Lesson:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        video_url:
          type: string
          nullable: true
        # ... other lesson fields
        materials:
          type: array
          description: Array of lesson materials
          items:
            $ref: '#/components/schemas/LessonMaterial'
      required:
        - id
        - title
